### ISSUE TITLE
QStringModel not in QtGui but QtCore on Pyside2

### ISSUE THREAD

**Issue by skoudoro** [pytest-dev/pytest-qt#205]
Hi, 

When I run `pytest`, I got this error:

`INTERNALERROR> AttributeError: module 'PySide2.QtGui' has no attribute 'QStringListModel'`

The doc [here](https://doc-snapshots.qt.io/qtforpython/PySide2/QtGui/QStringListModel.html) is a bit confusing for `QStringListModel` but this model seems to be in QtCore.

Furthermore, it seems this model is not present in all pyside2 as you can see [here](https://wiki.qt.io/PySide2_Missing_Bindings)

am I right or did I do something wrong?

**Comment by nicoddemus** [comment]
Hi @skoudoro, thanks for writing.

Can you please post the full traceback, along with python and PySide2 versions you are using?

For the record our CI uses PySide2 version 2.*:

https://github.com/pytest-dev/pytest-qt/blob/dcfc031aa248230fd22026881ea5a013d74f1c6b/.travis.yml#L23

And our latest build on Travis used `2.0.0.dev0`:

https://travis-ci.org/pytest-dev/pytest-qt/jobs/353785654

**Comment by skoudoro** [comment]
ok, Thanks for this information @nicoddemus. Here requested infos : 
windows 10 - python==3.6.4 - pysside2==5.9.0a1 - pytest-qt from conda-forge
I install pyside2 via `pip install --index-url=http://download.qt.io/snapshots/ci/pyside/5.9/latest/ pyside2 --trusted-host download.qt.io`

TraceBack:
-----------
```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\Users\skoudoro\AppData\Local\Continuum\Anaconda3\envs\mpsts-env-3\lib\site-packages\_pytest\main.py", line 103, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "C:\Users\skoudoro\AppData\Local\Continuum\Anaconda3\envs\mpsts-env-3\lib\site-packages\_pytest\config.py", line 914, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "C:\Users\skoudoro\AppData\Local\Continuum\Anaconda3\envs\mpsts-env-3\lib\site-packages\pluggy\__init__.py", line 628, in call_historic
INTERNALERROR>     res = self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "C:\Users\skoudoro\AppData\Local\Continuum\Anaconda3\envs\mpsts-env-3\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "C:\Users\skoudoro\AppData\Local\Continuum\Anaconda3\envs\mpsts-env-3\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "C:\Users\skoudoro\AppData\Local\Continuum\Anaconda3\envs\mpsts-env-3\lib\site-packages\pluggy\callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "C:\Users\skoudoro\AppData\Local\Continuum\Anaconda3\envs\mpsts-env-3\lib\site-packages\pluggy\callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "C:\Users\skoudoro\AppData\Local\Continuum\Anaconda3\envs\mpsts-env-3\lib\site-packages\pluggy\callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\Users\skoudoro\AppData\Local\Continuum\Anaconda3\envs\mpsts-env-3\lib\site-packages\pytestqt\plugin.py", line 187, in pytest_configure
INTERNALERROR>     qt_api.set_qt_api(config.getini('qt_api'))
INTERNALERROR>   File "C:\Users\skoudoro\AppData\Local\Continuum\Anaconda3\envs\mpsts-env-3\lib\site-packages\pytestqt\qt_compat.py", line 111, in set_qt_api
INTERNALERROR>     self.QStringListModel = QtGui.QStringListModel
INTERNALERROR> AttributeError: module 'PySide2.QtGui' has no attribute 'QStringListModel'
```

**Comment by nicoddemus** [comment]
Could you try using the development version of `pytest-qt` and check if changing this line:

https://github.com/pytest-dev/pytest-qt/blob/f36c1628777268b726ffb18e3f60c0ada7985efa/pytestqt/qt_compat.py#L111

To:

```python
self.QStringListModel = QtGui.QStringListModel if hasattr(QtGui, 'QStringListModel') else QtCore.QStringListModel
```

Works for you?

**Comment by altendky** [comment]
FYI, this is a reported bug in PySide2. 
 https://bugreports.qt.io/browse/PYSIDE-614

**Comment by nicoddemus** [comment]
Thanks @altendky for the reference

**Comment by rth** [comment]
> Could you try using the development version of pytest-qt and check if changing this line: Works for you?

I can reproduce this issue and confirm that the proposed fix works. Made a PR in https://github.com/pytest-dev/pytest-qt/pull/209

**Comment by nicoddemus** [comment]
Thanks @rth!

**Comment by nicoddemus** [comment]
`2.3.2` is out with this fix. 👍
